server:
  servlet:
    context-path: '/accounting-tax'
  port: 8088


spring:
  profiles: test
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password: 123
      driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    url: jdbc:postgresql://localhost:5432/accounting
    driverClassName: org.postgresql.Driver
    user: postgres
    password: test
    change-log: "db/changelog/db.changelog-test.sql"

jwt:
  secret: 'javeiro'
  jwtExpirationMs: 86400000